# Generated by Django 4.1.7 on 2023-04-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profileapp', '0003_alter_profile_loyalty_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='loyalty_point',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
